### ISSUE TITLE
Help with cfn-cloudfront (longrunning)

### ISSUE THREAD

**Issue by iDVB** [andrew-templeton/cfn-lambda#35]
First, thanks for a great boilerplate for Custom Resources. 
We've been using this a fair bit to create a number of minor CRs.

I wonder if someone wouldn't mind providing an example of how I could do the following.
I'm looking to build a CR that creates a very specific (hardcoded) type of CloudFront Distro as well as adds an entry to a DynamoDB table.

I already have a CR created and working that only does the DDB update. What I'm struggle to understand is how to CRUD a CloudFront Distro but restrict the values it takes in from CloudFormation.

Essentially the values it would take in...
Source: domain1.com
Target: domain2.com

Then it would create a CF distro that uses the Source as the `Alias`.

**Comment by andrew-templeton** [comment]
Could you provide some example snippets for the an example of the CR and the equivalent raw CF distribution? "My CR I'm envisioning <=> this normal template" would be very helpful. I'm not able to picture the scenario.

**Comment by iDVB** [comment]
Sure. I basically want the CR to 

1. Create/Update/Delete a CloudFront Distro (abstracting out all options and only asking user for domain name)
2. Create/Update/Delete a single row in a DDB table

Those two need to be transactional, meaning, they both need to happen or none.  I have a CR built with `crn-lambda` that does **# 2**. It's the **# 1** (needing long running) plus the need to transational that puts this out of my wheelhouse.

**Comment by andrew-templeton** [comment]
Hi, I am going to close this since I didn't ever get a snippet for the raw resource. I hope you were able to get this one solved.

**Comment by iDVB** [comment]
Sorry, specifically this is me thinking about Lambda@Edge and how they take
2hrs to delete (replica functions) but CloudFormation max timeout I think
is ~30mins.

I was contemplating building a custom resource that could somehow either
wait the 2hrs or mark edge functions as DeletionPolicy: Retain   And then
kick off some function to cron delete those after the fact once the 2hrs
was up.

**Comment by andrew-templeton** [comment]
Make a custom resource type called LambdaAtEdgeDeleter, and set the real resource to be Retain. You make your custom resource always return success immediately on Create and Update. You make the Delete command on the custom resource return success as soon as it kicks off the deletion of the main resource which was set to Retain. Then, the Deletion command is sent to the Lambda service during teardown, but does not actually wait for it complete, it just allows the command to run and assumes it will succeed in Deletion of the Lambda@Edge function if the initial API command to delete works. Does this help?

**Comment by iDVB** [comment]
Hmmm, I think if you call delete the edge functions before their replicas
are deleted (automated once the function is disassociated from cloud front,
takes approx. 2hrs) your call just fails and they will still be there when
the dust settles. The call to delete needs to happen after the 2hrs. This
is why I was thinking of long running custom resource. But maybe I should
just use cloudtrail and handle this as a cron?

**Comment by andrew-templeton** [comment]
Reopening since I have more concrete understanding of the ask. 

Ah, my mistake, I didn't grok the replica portion of the issue. 

I think a good feature proposal could be as such: 

Base long-running off of CloudWatch Events, and have the custom resources automatically allow (1) invocation from CloudWatch events on the resource policy for the Lambda (2) allow add permission grants to allow for creation of Rules in CloudWatch Events, with a Condition on the IAM statement that allows the Lambda to also create schedules with a target of the Lambda itself. 

So a long-running would, instead of chain-self-invoking, launch a rate(5 minute) (or configurable rate) CloudWatch event scheduled task, which evaluates the LongRunning logic. When the LongRunning invocation completes or errors out, remove the CloudWatch Event task. 

Additionally, I believe this would be resolved by, in conjunction with the above, making a custom resource that actually makes a nested stack with these ultra-long running resources. The nested stack should contain the Replicas + the Lambda@Edge functions. Instead of returning success on proper Deletion init for the function itself, return a success on proper Deletion init for the nested stack which contains these resources. On the backend, the deletion of the main stack proceeds as soon as the deletion of the substack initiates, and the substack can handle the actual, super-long deletion of interdependent resources that take 2+ hours. Would this meet your goals?
